# Generated by Django 4.1 on 2024-02-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studentmgmt", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_name", models.CharField(max_length=200)),
            ],
        ),
    ]
